export const THINKING_WORDS = [
	"Marinating",
	"Percolating",
	"Noodling",
	"Vibing",
	"Ruminating",
	"Spelunking",
	"Untangling",
	"Wrangling",
	"Divining",
	"Conjuring",
	"Puzzling",
	"Simmering",
	"Rummaging",
	"Excavating",
	"Bikeshedding",
	"Overthinking",
	"Channeling",
	"Summoning",
	"Fermenting",
	"Coalescing",
	"Vibrating",
	"Brewing",
	"Loitering",
	"Deliberating",
	"Cogitating",
	"Scheming",
] as const;
